
spring:
  datasource:
    platform: postgres
#    url: jdbc:postgresql://35.187.23.240:5432/bmg_vault_test
    url: jdbc:postgresql://172.16.1.241:5432/bmg_vault_test
    username: postgres
    password: ba2zcCgGHBGoPpmf
    initialization-mode: always
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  main:
    web-environment: true

server:
  port: 8080
  use-forward-headers: true

management:
  server:
    port: 8090
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "info"
          - "readiness"
  metrics:
    tags:
      application: bmg-cloud-vault

